#!/usr/bin/env sh
set -e			# Stop on first error

CC="cc"
CFLAGS="-std=c89"

CFLAGS="$CFLAGS -Wall -Wextra -Wshadow -pedantic"
CFLAGS="$CFLAGS -Wmissing-declarations -Wswitch-enum"
CFLAGS="$CFLAGS -Wno-missing-braces"

CFLAGS="$CFLAGS -D_XOPEN_SOURCE=500"		# For strdup()
CFLAGS="$CFLAGS -D_POSIX_C_SOURCE=200112L"	# For setenv()

# CFLAGS="$CFLAGS -ggdb"

$CC $CFLAGS -c gmi.c   &
$CC $CFLAGS -c gph.c   &
wait

$CC $CFLAGS -o yupa *.o main.c -lssl -lcrypto
    
rm *.o		# Cleanup
