#!/usr/bin/env sh
set -e # Stop on first error

CC="cc"
CFLAGS="-Wall -Wextra -Wshadow -Wmissing-declarations -Wswitch-enum -Wno-deprecated-declarations -pedantic -std=c99"

$CC $CFLAGS -c util.c
$CC $CFLAGS -c uri.c
$CC $CFLAGS -c fetch.c
$CC $CFLAGS -c link.c
$CC $CFLAGS -c gmi.c
$CC $CFLAGS -c gph.c
$CC $CFLAGS -c html.c
$CC $CFLAGS -o yupa *.o main.c -lssl -lcrypto
